from . import view_home
from . import view_registration
from . import view_site_tos
from . import view_manage_flashcards
from . import view_user_manage_flashcards
from . import view_user_flashcards
from . import view_user_favorites
from . import view_user
from . import view_manage_user_flashcards
from . import view_manage_users